name: Backend Quality Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NX_NO_CLOUD: true
    strategy:
      matrix:
        node-version:
          - 22.11.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Linter'
        run: npm run lint
      - name: 'Test econogest apps'
        run: npm run test:econogest
      - name: 'Test transactions libs'
        run: npm run test:transactions
